config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, controllers: {
    sessions: 'admin/sessions'
  }

  devise_for :customers, skip: [:registrations]
  as :customer do
    get 'sign_up', to: 'devise/registrations#new', as: :new_customer_registration
    post '', to: 'devise/registrations#create', as: :customer_registration
  end

  root to: 'public/homes#top'
  get 'about' => 'public/homes#about'

  scope module: :public do
    resource :customers, only: [:edit, :update]
    get 'customers/my_page' => 'customers#show'
    patch 'customers/withdraw' => 'customers#withdraw'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    resources :shipping_addresses, only: [:index, :create, :edit, :update, :destroy]
    resources :products, only: [:index, :show]
    delete 'cart_products/destroy_all' => 'cart_products#destroy_all'
    resources :cart_products, only: [:index, :create, :update, :destroy]
    post 'orders/confirm' => 'orders#confirm'
    get 'orders/complete' => 'orders#complete'
    resources :orders, only: [:new, :index, :show, :create]
  end

  namespace :admin do
    get '/' => 'homes#top'
    resources :customers, only: [:index, :show, :edit, :update]
    resources :products, except: [:destroy]
    resources :orders, only: [:show, :update] do
      resources :ordered_products, only: [:update]
    end
    resources :genres, only: [:index, :edit, :create, :update]
  end






end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord

  belongs_to :customer
  belongs_to :product

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :shipping_addresses, dependent: :destroy
  has_many :cart_products, dependent: :destroy
  has_many :orders, dependent: :destroy
  
  enum is_deleted: {"退会": true, "有効": false}

    def active_for_authentication?
        super && (self.is_deleted === "有効")
    end
    
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postcode, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true

  def full_name
    self.last_name + self.first_name
  end

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :products, dependent: :destroy

end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :ordered_products, dependent: :destroy

  enum payment_method:[:"クレジットカード", :"銀行振込"]
  enum order_status:[:"入金待ち", :"入金確認", :"製作中", :"発送準備中", :"発送済み"], _prefix: true
end

app/models/ordered_product.rb
class OrderedProduct < ApplicationRecord

  belongs_to :order
  belongs_to :product
  
  enum production_status:[:"製作不可", :"製作待ち", :"製作中", :"製作完了"], _prefix: true

end

app/models/product.rb
class Product < ApplicationRecord

  has_many :cart_products, dependent: :destroy
  has_many :ordered_products, dependent: :destroy
  belongs_to :genre
  attachment :image


  enum is_active:{"販売中": true, "販売停止中": false }

end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord

  belongs_to :customer

  def full_address
    self.postcode + " " + self.address + " " + self.name
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  def index
    @customers = Customer.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path(@customer)
  end

  def customer_params
    	params.require(:customer).permit(:last_name, :first_name, :last_name_kana,
    	:first_name_kana, :email, :postcode, :address, :phone_number, :is_deleted)
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  def top
    @orders = Order.page(params[:page]).reverse_order.per(10)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  def show
    @order = Order.find(params[:id])
    @order_product = @order.ordered_products
  end

def update
  @order = Order.find(params[:id])
  @order.update(order_params)
  @order_product = @order.ordered_products
  if @order.order_status == "入金確認"
    @order_product.update_all(production_status: "製作待ち" )
  end
  redirect_to admin_order_path(@order)
end

  private
  def order_params
    params.require(:order).permit(:payment_method, :postcode, :address, :name, :postage, :total_price, :order_status)
  end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @products = Product.all
    @products = Product.page(params[:page]).per(8)
  end

  def new
    @product = Product.new
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(product_params)
    @product.save(product_params)
    redirect_to admin_product_path(@product)
  end

  def update
    @product = Product.find(params[:id])
    @product.update(product_params)
    redirect_to admin_product_path(params[:id])
  end

    private

  def product_params
    params.require(:product).permit(:genre_id, :image, :name, :description, :price, :is_active)
  end

end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admins::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    root_path
  end
  
  def after_sign_out_path_for(resource)
    root_path
  end
  
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:
    [:last_name, :first_name, :last_name_kana, :first_name_kana, :email,
    :postcode, :address, :phone_number, :password, :password_confirmation])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row mb-5">
    <h3><span class="bg-light"><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</span></h3>
  </div>
<%= form_with model: @customer, url: admin_customer_path(@customer), method: :patch, local:true do |f| %>
  <div class="row">
    <div class="col-md-3">会員ID
    </div>
    <div class="form-group col-md-3">
      <%= @customer.id %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3">
      <%= f.label "氏名" %>
    </div>
    <div class="form-group col-md-3">
      <%= f.text_field :last_name, class: "form-control" %>
    </div>
    <div class="form-group col-md-3">
      <%= f.text_field :first_name, class: "form-control"%>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3">
      <%= f.label "フリガナ" %>
    </div>
    <div class="form-group col-md-3">
      <%= f.text_field :last_name_kana, class: "form-control" %>
    </div>
    <div class="form-group col-md-3">
      <%= f.text_field :first_name_kana, class: "form-control" %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3">
      <%= f.label "郵便番号(ハイフンなし)" %>
    </div>
    <div class="form-group col-md-3">
      <%= f.text_field :postcode, class: "form-control" %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3">
      <%= f.label "住所" %>
    </div>
    <div class="form-group col-md-6">
      <%= f.text_field :address, class: "form-control" %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3">
      <%= f.label "電話番号(ハイフンなし)" %>
    </div>
    <div class="form-group col-md-3">
      <%= f.text_field :phone_number, class: "form-control" %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3">
      <%= f.label "メールアドレス" %>
    </div>
    <div class="form-group col-md-3">
      <%= f.email_field :email, class: "form-control" %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3">
      <%= f.label "会員ステータス" %>
    </div>
    <div class="col-md-3">
      <%= f.radio_button :is_deleted, :"有効" %>
      <%= f.label :is_deleted, "有効", {value: :true, style: "display: inline-block;"} %>
      <%= f.radio_button :is_deleted, :"退会" %>
      <%= f.label :is_deleted, "退会", {value: :false, style: "display: inline-block;"} %>
    </div>
  </div>
  <div class="row mb-3 mt-3">
  <div class="col-md-3 offset-md-3">
    <%= f.submit "変更を保存", class: "btn btn-success btn-block p-2" %>
  </div>
  </div>
<% end %>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row mb-3">
    <div class="col-md-2 col-md-offset-10">
      <h3><span class="bg-light">会員一覧</span></h3>
    </div>
  </div>
  <div class="row">
    <div class="col-md-10 mx-auto">
      <table class="table">
        <thead class="bg-light">
          <tr>
            <th>会員ID</th>
            <th>⽒名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <% @customers.each do |customer| %>
        <tbody>
          <tr>
            <td><%= customer.id %></td>
            <td>
              <%= link_to admin_customer_path(customer.id), class: "text-body" do %>
                <%= customer.last_name %><%= customer.first_name %>
              <% end %>
            </td>
            <td><%= customer.email %></td>
            <td><%= customer.is_deleted %></td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
    <div class="row">
      <div class="col-auto mx-auto"><%= paginate @customers %></div>
    </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row mb-4">
    <div class="col">
      <h4><span class="bg-light"><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</span></h4>
    </div>
  </div>
<div class="row mb-3">
  <div class="col-md-3">会員ID</div>
  <div class="col-md-8"><%= @customer.id %></div>
</div>
<div class="row mb-3">
  <div class="col-md-3">氏名</div>
  <div class="col-md-8">  <%= @customer.last_name %>&nbsp;<%= @customer.first_name %></div>
</div>
<div class="row mb-3">
  <div class="col-md-3">フリガナ</div>
  <div class="col-md-8"><%= @customer.last_name_kana %>&nbsp;<%= @customer.first_name_kana %></div>
</div>
<div class="row mb-3">
  <div class="col-md-3">郵便番号</div>
  <div class="col-md-8"><%= @customer.postcode %></div>
</div>
<div class="row mb-3">
  <div class="col-md-3">住所</div>
  <div class="col-md-8"><%= @customer.address %></div>
</div>
<div class="row mb-3">
  <div class="col-md-3">電話番号</div>
  <div class="col-md-8"><%= @customer.phone_number %></div>
</div>
<div class="row mb-3">
  <div class="col-md-3">メールアドレス</div>
  <div class="col-md-8"><%= @customer.email %></div>
</div>
<div class="row mb-3">
  <div class="col-md-3">会員ステータス</div>
  <div class="col-md-8"><%= @customer.is_deleted %></div>
</div>
<div class="row mb-2">
  <div class="col-md-2 offset-md-3">
    <%= link_to "編集する", edit_admin_customer_path(@customer), class: "btn btn-success" %>
  </div>
  <div class="col-md-7 text-left">
    <%= link_to "注文履歴一覧を見る", admin_path, class: "btn btn-primary" %>
  </div>
</div>
</div>