config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, controllers: {
    sessions: 'admin/sessions'
  }

  devise_for :customers, skip: [:registrations]
  as :customer do
    get 'sign_up', to: 'devise/registrations#new', as: :new_customer_registration
    post '', to: 'devise/registrations#create', as: :customer_registration
  end

  root to: 'public/homes#top'
  get 'about' => 'public/homes#about'

  scope module: :public do
    resource :customers, only: [:edit, :update]
    get 'customers/my_page' => 'customers#show'
    patch 'customers/withdraw' => 'customers#withdraw'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    resources :shipping_addresses, only: [:index, :create, :edit, :update, :destroy]
    resources :products, only: [:index, :show]
    delete 'cart_products/destroy_all' => 'cart_products#destroy_all'
    resources :cart_products, only: [:index, :create, :update, :destroy]
    post 'orders/confirm' => 'orders#confirm'
    get 'orders/complete' => 'orders#complete'
    resources :orders, only: [:new, :index, :show, :create]
  end

  namespace :admin do
    get '/' => 'homes#top'
    resources :customers, only: [:index, :show, :edit, :update]
    resources :products, except: [:destroy]
    resources :orders, only: [:show, :update] do
      resources :ordered_products, only: [:update]
    end
    resources :genres, only: [:index, :edit, :create, :update]
  end






end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord

  belongs_to :customer
  belongs_to :product

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :shipping_addresses, dependent: :destroy
  has_many :cart_products, dependent: :destroy
  has_many :orders, dependent: :destroy
  
  enum is_deleted: {"退会": true, "有効": false}

    def active_for_authentication?
        super && (self.is_deleted === "有効")
    end
    
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postcode, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true

  def full_name
    self.last_name + self.first_name
  end

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :products, dependent: :destroy

end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :ordered_products, dependent: :destroy

  enum payment_method:[:"クレジットカード", :"銀行振込"]
  enum order_status:[:"入金待ち", :"入金確認", :"製作中", :"発送準備中", :"発送済み"], _prefix: true
end

app/models/ordered_product.rb
class OrderedProduct < ApplicationRecord

  belongs_to :order
  belongs_to :product
  
  enum production_status:[:"製作不可", :"製作待ち", :"製作中", :"製作完了"], _prefix: true

end

app/models/product.rb
class Product < ApplicationRecord

  has_many :cart_products, dependent: :destroy
  has_many :ordered_products, dependent: :destroy
  belongs_to :genre
  attachment :image


  enum is_active:{"販売中": true, "販売停止中": false }

end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord

  belongs_to :customer

  def full_address
    self.postcode + " " + self.address + " " + self.name
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  def top
    @orders = Order.page(params[:page]).reverse_order.per(10)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  def show
    @order = Order.find(params[:id])
    @order_product = @order.ordered_products
  end

def update
  @order = Order.find(params[:id])
  @order.update(order_params)
  @order_product = @order.ordered_products
  if @order.order_status == "入金確認"
    @order_product.update_all(production_status: "製作待ち" )
  end
  redirect_to admin_order_path(@order)
end

  private
  def order_params
    params.require(:order).permit(:payment_method, :postcode, :address, :name, :postage, :total_price, :order_status)
  end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @products = Product.all
    @products = Product.page(params[:page]).per(8)
  end

  def new
    @product = Product.new
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(product_params)
    @product.save(product_params)
    redirect_to admin_product_path(@product)
  end

  def update
    @product = Product.find(params[:id])
    @product.update(product_params)
    redirect_to admin_product_path(params[:id])
  end

    private

  def product_params
    params.require(:product).permit(:genre_id, :image, :name, :description, :price, :is_active)
  end

end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected
    def after_sign_in_path_for(resource)
    admin_path
    end

    def after_sign_out_path_for(resource)
      new_admin_session_path
    end
  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admins::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    root_path
  end
  
  def after_sign_out_path_for(resource)
    root_path
  end
  
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:
    [:last_name, :first_name, :last_name_kana, :first_name_kana, :email,
    :postcode, :address, :phone_number, :password, :password_confirmation])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
  <div class="row">
    <h4 class="col offset-md-1 mb-md-5">ジャンル編集</h4>
  </div>
  <div class="row">
    <div class="col-md-2 offset-md-1 mb-md-5">
      <p>ジャンル名</p>
    </div>
    <div class="col">
      <%= form_with model: @genre, url: admin_genre_path, method: :patch, local:true do |f| %>
        <%= f.text_field :name %>
        <%= f.submit '変更を保存',class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
  <div class="row">
    <h4 class="col offset-md-1 mb-md-5">ジャンル一覧・追加</h4>
  </div>
  <div class="row">
    <div class="col-md-2 offset-md-1 mb-md-5">
      <p>ジャンル名</p>
    </div>
    <div class="col">
      <%= form_with model: @genre, url: admin_genres_path, method: :post, local:true do |f| %>
        <%= f.text_field :name, :placeholder => "ジャンル名" %>
        <%= f.submit '新規登録',class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-5 offset-md-1">
      <table class="table">
        <thead class="thead-light">
          <tr>
            <th>ジャンル名</th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @genres.each do |genre| %>
            <tr>
              <td>
                <%= genre.name %>
              </td>
              <td>
                <%= link_to "編集する", edit_admin_genre_path(genre),class: "btn btn-success" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <h4 class="col offset-md-1 mb-md-5">注文履歴詳細</h4>
  </div>
  <div class="row mb-md-5">
    <div class="col-md-2 mb-md-2">購入者</div>
    <div class="col-md-10">
      <%= link_to admin_customer_path(@order) do %>
        <%= @order.customer.full_name %>
      <% end %>
    </div>
    <div class="col-md-2 mb-md-2">注文日</div>
    <div class="col-md-10">
      <%= @order.created_at.strftime('%Y/%m/%d') %>
    </div>
    <div class="col-md-2 mb-md-2">配送先</div>
    <div class="col-md-10">
      <p><%= @order.postcode %><%= @order.address %></p>
      <p><%= @order.name %></p>
    </div>
    <div class="col-md-2 mb-md-2">支払方法</div>
    <div class="col-md-10">
      <%= @order.payment_method %>
    </div>
    <div class="col-md-2 mb-md-2">注文ステータス</div>
    <div class="col-md-5">
      <div class="form-group">
        <div class="form-inline">
      <%= form_with model: @order, url: admin_order_path(@order), method: :patch, local:true do |f| %>
        <%= f.select :order_status, Order.order_statuses.keys.map {|k| [k, k]}, {}, { class: "form-control", style: 'margin-right: 20px;', data: {} } %>
        <%= f.submit '更新', class: 'btn btn-success inline' %>
      <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-9">
      <table class="table">
        <thead class="thead-light">
          <tr>
            <th>商品名</th>
            <th>単価（税込）</th>
            <th>数量</th>
            <th>小計</th>
            <th>製作ステータス</th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @order_product.each do |order_product| %>
            <tr>
              <td>
                <%= order_product.product.name %>
              </td>
              <td>
                <%= (order_product.with_tax_price).to_s(:delimited) %>
              </td>
              <td>
                <%= order_product.quantity %>
              </td>
              <td>
                <%= (order_product.with_tax_price * order_product.quantity).to_s(:delimited) %>
              </td>
                <%= form_with(model:[:admin, @order, order_product], local: true) do |f| %>
              <td>
                <%= f.select :production_status, OrderedProduct.production_statuses.keys.map {|k| [k, k]}, {}, { class: "form-control", style: 'margin-bottom: 15px;', data: {} } %>
              </td>
              <td>
                <%= f.submit '更新', class: 'btn btn-success' %>
              </td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class="col-md-3 mt-auto">
      <ul class="list-inline">
        <li class="list-inline-item">商品合計</li>
        <li class="list-inline-item"><%= (@order.total_price).to_s(:delimited) %>円</li>
      </ul>
      <ul class="list-inline">
        <li class="list-inline-item">送料</li>
        <li class="list-inline-item"><%= @order.postage %>円</li>
      </ul>
      <ul class="list-inline">
        <li class="list-inline-item">請求金額合計</li>
        <li class="list-inline-item"><%= (@order.total_price + @order.postage).to_s(:delimited) %>円</li>
      </ul>
    </div>
  </div>

app/views/admin/products/edit.html.erb
<div class='container'>
  <div class='row'>
    <h4 class="col offset-md-1">商品編集</h4>
  </div>

  <%= form_with model: @product, url: admin_product_path, method: :patch, local:true do |f| %>
  <div class='row mt-md-5'>
    <div class="col-md-2 offset-md-2 ">
      商品画像
    </div>
    <div class="col-md-8">
      <%= f.attachment_field :image %>
    </div>
  </div>

  <div class='row mt-md-3'>
    <div class="col-md-2 offset-md-2">
      商品名
    </div>
    <div class="col-md-8">
      <%= f.text_field :name, :size=> 40 %>
    </div>
  </div>

  <div class='row mt-md-3'>
    <div class="col-md-2 offset-md-2">
      商品説明
    </div>
    <div class="col-md-8">
      <%= f.text_area :description, size: "39x10" %>
    </div>
  </div>

  <div class='row mt-md-3'>
    <div class="col-md-2 offset-md-2">
      ジャンル
    </div>
    <div class="col-md-8">
        <%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "選択して下さい" %>
    </div>
  </div>

  <div class='row mt-md-3'>
    <div class="col-md-2 offset-md-2">
      税抜価格
    </div>
    <div class="col-md-8">
      <%= f.text_field :price, :size=> 40 %>
    </div>
  </div>

  <div class='row mt-md-3'>
    <div class="col-md-2 offset-md-2">
      販売ステータス
    </div>
    <div class="col-md-4">
      <%= f.radio_button :is_active, :"販売中", checked: true %>
        <%= f.label :is_active, "販売中", {value: :true, style: "display: inline-block;"} %>
        <%= f.radio_button :is_active, :"販売停止中" %>
        <%= f.label :is_active, "販売停止中", {value: :false, style: "display: inline-block;"} %>
    </div>
  </div>

  <div class="row mt-md-3">
    <div class="col-auto mx-auto">
      <%= f.submit '投稿', class: 'btn btn-success submit_botton' %></div>
  </div>
  <% end %>
</div>

app/views/admin/products/index.html.erb
<div class='container'>
  <div class='row'>
    <h4 class='col offset-md-1 mb-md-5'>
      商品一覧
    </h4>
    <div class='mb-3 text-right'>
      <button type="button" class="btn btn-light shadow-sm rounded-circle p-0" style="width:2rem;height:2rem;">
        <%= link_to "＋", new_admin_product_path, class:"no-underline" %>
      </button>
    </div>
  </div>
  <div class='row'>
    <div class="col offset-md-1">
      <table class="table">
        <thead class="thead-light">
        <tr>
          <th>商品ID</th>
          <th>商品名</th>
          <th>税抜価格</th>
          <th>ジャンル</th>
          <th>ステータス</th>
        </tr>
        </thead>

        <tbody>
          <% @products.each do |products| %>
            <tr>
              <td><%= products.id %></td>
              <td>
                <%= link_to admin_product_path(products.id) do %>
                  <%= products.name %>
                <% end %>
              </td>
              <td><%= (products.price).to_s(:delimited) %></td>
              <td><%= products.genre.id %></td>
              <td><%= products.is_active %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-auto mx-auto"><%= paginate @products %></div>
  </div>
</div>

app/views/admin/products/new.html.erb
<div class='container'>
  <div class='row'>
    <h4 class="col offset-md-1">商品新規登録</h4>
  </div>

  <%= form_with model: @product, url: admin_products_path, method: :post, local:true do |f| %>
  <div class='row mt-md-5'>
    <div class="col-md-2 offset-md-2 ">
      商品画像
    </div>
    <div class="col-md-8">
      <%= f.attachment_field :image %>
    </div>
  </div>

  <div class='row mt-md-3'>
    <div class="col-md-2 offset-md-2">
      商品名
    </div>
    <div class="col-md-8">
      <%= f.text_field :name, :size=> 40 %>
    </div>
  </div>

  <div class='row mt-md-3'>
    <div class="col-md-2 offset-md-2">
      商品説明
    </div>
    <div class="col-md-8">
      <%= f.text_area :description, size: "39x10" %>
    </div>
  </div>

  <div class='row mt-md-3'>
    <div class="col-md-2 offset-md-2">
      ジャンル
    </div>
    <div class="col-md-8">
        <%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "選択して下さい" %>
    </div>
  </div>

  <div class='row mt-md-3'>
    <div class="col-md-2 offset-md-2">
      税抜価格
    </div>
    <div class="col-md-8">
      <%= f.text_field :price, :size=> 40 %>
    </div>
  </div>

  <div class='row mt-md-3'>
    <div class="col-md-2 offset-md-2">
      販売ステータス
    </div>
    <div class="col-md-4">
      <%= f.radio_button :is_active, :"販売中", checked: true %>
        <%= f.label :is_active, "販売中", {value: :true, style: "display: inline-block;"} %>
        <%= f.radio_button :is_active, :"販売停止中" %>
        <%= f.label :is_active, "販売停止中", {value: :false, style: "display: inline-block;"} %>
    </div>
  </div>
  <div class="row mt-md-3">
    <div class="col-auto mx-auto">
      <%= f.submit '投稿', class: 'btn btn-success submit_botton' %></div>
  </div>
  <% end %>
</div>

app/views/admin/products/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-offset-1 col-md-10">
      <h2 class="customer_title">商品詳細</h2>
        <div class="row">
          <div>
            <%= attachment_image_tag(@product, :image, fallback: "no_image.jpg", size:'250x200') %>
          </div>
          <div class=col>
            <table class="table">
              <tr>
                <td>商品名</td>
                <td><%= @product.name %></td>
              </tr>
              <tr>
                <td>商品説明</td>
                <td><%= @product.description %></td>
              </tr>
              <tr>
                <td>ジャンル</td>
                <td><%= @product.genre_id %></td>
              </tr>
              <tr>
                <td>税込価格(税抜価格)</td>
                <td><%= ((@product.price*1.10).to_i).to_s(:delimited) %>&nbsp;(<%= (@product.price).to_s(:delimited) %>)円</td>
              </tr>
              <tr>
                <td>販売ステータス</td>
                <td>販売中</td>
              </tr>
            </table>
            <%= link_to '編集する', edit_admin_product_path, class: 'btn btn-success btn-lg' %>
          </div>
        </div>
　  </div>
  </div>
</div>