config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, controllers: {
    sessions: 'admin/sessions'
  }

  devise_for :customers, skip: [:registrations]
  as :customer do
    get 'sign_up', to: 'devise/registrations#new', as: :new_customer_registration
    post '', to: 'devise/registrations#create', as: :customer_registration
  end

  root to: 'public/homes#top'
  get 'about' => 'public/homes#about'

  scope module: :public do
    resource :customers, only: [:edit, :update]
    get 'customers/my_page' => 'customers#show'
    patch 'customers/withdraw' => 'customers#withdraw'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    resources :shipping_addresses, only: [:index, :create, :edit, :update, :destroy]
    resources :products, only: [:index, :show]
    delete 'cart_products/destroy_all' => 'cart_products#destroy_all'
    resources :cart_products, only: [:index, :create, :update, :destroy]
    post 'orders/confirm' => 'orders#confirm'
    get 'orders/complete' => 'orders#complete'
    resources :orders, only: [:new, :index, :show, :create]
  end

  namespace :admin do
    get '/' => 'homes#top'
    resources :customers, only: [:index, :show, :edit, :update]
    resources :products, except: [:destroy]
    resources :orders, only: [:show, :update] do
      resources :ordered_products, only: [:update]
    end
    resources :genres, only: [:index, :edit, :create, :update]
  end






end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord

  belongs_to :customer
  belongs_to :product

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :shipping_addresses, dependent: :destroy
  has_many :cart_products, dependent: :destroy
  has_many :orders, dependent: :destroy
  
  enum is_deleted: {"退会": true, "有効": false}

    def active_for_authentication?
        super && (self.is_deleted === "有効")
    end
    
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postcode, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true

  def full_name
    self.last_name + self.first_name
  end

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :products, dependent: :destroy

end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :ordered_products, dependent: :destroy

  enum payment_method:[:"クレジットカード", :"銀行振込"]
  enum order_status:[:"入金待ち", :"入金確認", :"製作中", :"発送準備中", :"発送済み"], _prefix: true
end

app/models/ordered_product.rb
class OrderedProduct < ApplicationRecord

  belongs_to :order
  belongs_to :product
  
  enum production_status:[:"製作不可", :"製作待ち", :"製作中", :"製作完了"], _prefix: true

end

app/models/product.rb
class Product < ApplicationRecord

  has_many :cart_products, dependent: :destroy
  has_many :ordered_products, dependent: :destroy
  belongs_to :genre
  attachment :image


  enum is_active:{"販売中": true, "販売停止中": false }

end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord

  belongs_to :customer

  def full_address
    self.postcode + " " + self.address + " " + self.name
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  def top
    @orders = Order.page(params[:page]).reverse_order.per(10)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  def show
    @order = Order.find(params[:id])
    @order_product = @order.ordered_products
  end

def update
  @order = Order.find(params[:id])
  @order.update(order_params)
  @order_product = @order.ordered_products
  if @order.order_status == "入金確認"
    @order_product.update_all(production_status: "製作待ち" )
  end
  redirect_to admin_order_path(@order)
end

  private
  def order_params
    params.require(:order).permit(:payment_method, :postcode, :address, :name, :postage, :total_price, :order_status)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    root_path
  end
  
  def after_sign_out_path_for(resource)
    root_path
  end
  
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:
    [:last_name, :first_name, :last_name_kana, :first_name_kana, :email,
    :postcode, :address, :phone_number, :password, :password_confirmation])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
   <body>
     <header class="navbar shadow-sm">
       <div>
         <ul class="navbar-nav">
           <nav class="navbar navbar-expand-lg">
             <li class="nav-item d-flex align-items-center">
               <% if admin_signed_in? %>
                 <%= link_to "ながのCAKE", admin_path, class: 'navbar-brand' %>
               <% else %>
                 <%= link_to "ながのCAKE", root_path, class: 'navbar-brand' %>
               <% end %>
             </li>
         </ul>
       </div>
       <ul class="nav justify-content-end">
         <% if customer_signed_in? %>
           <li class="nav-item d-flex align-items-center">
             ようこそ、<%= current_customer.last_name %>さん！
           </li>
           <li class="nav-item">
             <%= link_to "マイページ", customers_my_page_path, class: 'nav-link text-dark' %>
           </li>
           <li class="nav-item">
             <%= link_to "商品一覧", products_path, class: 'nav-link text-dark' %>
           </li>
           <li class="nav-item">
             <%= link_to "カート", cart_products_path, class: 'nav-link text-dark' %>
           </li>
           <li class="nav-item">
             <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'nav-link text-dark' %>
           </li>
         <% elsif admin_signed_in? %>
           <li class="nav-item">
             <%= link_to "商品一覧", admin_products_path, class: 'nav-link text-dark' %>
           </li>
           <li class="nav-item">
             <%= link_to "会員一覧", admin_customers_path, class: 'nav-link text-dark' %>
           </li>
           <li class="nav-item">
             <%= link_to "注文履歴一覧", admin_path, class: 'nav-link text-dark' %>
           </li>
           <li class="nav-item">
             <%= link_to "ジャンル一覧", admin_genres_path, class: 'nav-link text-dark' %>
           </li>
           <li class="nav-item">
             <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link text-dark' %>
           </li>
         <% else %>
           <li class="nav-item">
             <%= link_to "About", about_path, class: 'nav-link text-dark' %>
           </li>
           <li class="nav-item">
             <%= link_to "商品一覧", products_path, class: 'nav-link text-dark' %>
           </li>
           <li class="nav-item">
             <%= link_to "新規登録", new_customer_registration_path, class: 'nav-link text-dark' %>
           </li>
           <li class="nav-item">
             <%= link_to "ログイン", new_customer_session_path, class: 'nav-link text-dark' %>
           </li>
         <% end %>
       </ul>
     </nav>
   </header>
   <div>
     <%= yield %>
   </div>
   <footer>
   </footer>
   </body>
 </html>